apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: esendit-alerts
  namespace: monitoring
  labels:
    release: monitoring
spec:
  groups:
    - name: esendit-basic
      rules:
        - alert: EsenditBackendDown
          expr: up{namespace="esendit"} == 0
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: "eSendIT backend target is DOWN"

        - alert: EsenditPodsRestarting
          expr: increase(kube_pod_container_status_restarts_total{namespace="esendit"}[10m]) > 3
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "eSendIT pods restarting frequently"
