apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: esendit-backend
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - esendit
  selector:
    matchLabels:
      monitor: esendit
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
